### ISSUE TITLE
ErmRest Data Utils should not assume Foreign Keys are defined

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/ErmrestDataUtils#1]
When running the test suite with a schema that includes a table without any foreign keys defined, the following error is displayed as part of the console output:

```
TypeError: Cannot read property 'forEach' of undefined
    at /Users/jchudy/workspace/ermrestjs/node_modules/ermrest-data-utils/model/association.js:82:25
```

Inspecting this code, points out that there is an iterator over `table['foreign_keys']`. This will fail if there is no `foreign_keys` array. I talked to Hongsuda about it, and we should allow a user to define a table without foreign keys.

**Comment by chiragsanghvi** [comment]
It has been fixed in [this commit](https://github.com/informatics-isi-edu/ErmrestDataUtils/commit/d98e3dd7d829526d218222a0097173740dc5a266).
